# Generated by Django 2.1.7 on 2020-11-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
